#!/usr/bin/env bash

# This script transfers a file to a remote server using SCP.
# It requires four arguments: PATH_TO_FILE, IP, USERNAME, and PATH_TO_SSH_KEY.
# PATH_TO_FILE will be copied to the remote server at the user's home directory.
# The SSH key specified by PATH_TO_SSH_KEY will be used for authentication.

if [ $# -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_to_file=$1
ip=$2
username=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$ip:~/"
