#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform 301 Moved Permanently

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create the custom index.html with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Backup the original NGINX configuration as a precaution
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Add the redirection rule
sudo sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://github.com/KillerA-z1;\n    }' /etc/nginx/sites-available/default

# Restart NGINX to apply the changes
sudo service nginx restart