#!/usr/bin/env bash
# Configure Nginx to have a custom 404 page

# Create the custom 404 page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Backup the original NGINX configuration as a precaution
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Add the redirection rule
sudo sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://github.com/KillerA-z1;\n    }' /etc/nginx/sites-available/default

# Configure Nginx to use the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/error_page 404 \/404.html;/a \    error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo sed -i 's|error_page 404 /404.html;|error_page 404 /custom_404.html;|' /etc/nginx/sites-available/default

# Restart NGINX to apply the changes
sudo service nginx restart