#!/usr/bin/env bash
# Configure Nginx to have a custom 404 page

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Backup the original NGINX configuration as a precaution
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Configure Nginx to use the custom 404 page
sudo sed -i '/error_page 404 \/404.html;/a \    error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo sed -i 's|error_page 404 /404.html;|error_page 404 /custom_404.html;|' /etc/nginx/sites-available/default

# Restart NGINX to apply the changes
sudo service nginx restart