#!/usr/bin/env bash
#This Bash script installs and configures HAProxy on a Ubuntu server to load balance HTTP traffic.

# Update and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  10000
    timeout server  10000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 240607-web-01 52.204.69.114:80 check
    server 240607-web-02 54.158.80.235:80 check
EOF

# Ensure correct hostnames
sudo hostnamectl set-hostname 240607-lb-01

# Test the HAProxy configuration
sudo haproxy -c -V -f /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Restart HAProxy to apply changes
sudo service haproxy restart
