#!/usr/bin/env bash
# This script creates a symbolic link between the default Nginx configuration file

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart

