#!/usr/bin/env bash
# This script creates a symbolic link between the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart

