#!/usr/bin/env bash
# a script that Creates the file /var/run/myscript.pid containing its PID.

# Create the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid;

trap "echo I hate the kill command; sudo rm /var/run/myscript.pid" SIGTERM;
trap "echo Y U no love me?!; exit" SIGINT;
trap "sudo rm /var/run/myscript.pid; exit" SIGQUIT;

while true
do
    echo "To infinity and beyond";
    sleep 2;
done
