#!/usr/bin/env bash
# Bash script that Creates the file /var/run/myscript.pid containing its PID and Displays To infinity and beyond indefinitely,I hate the kill command when receiving a SIGTERM signal,Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

# Create the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid;

trap "echo I hate the kill command; sudo rm /var/run/myscript.pid" SIGTERM;
trap "echo Y U no love me?!; exit" SIGINT;
trap "sudo rm /var/run/myscript.pid; exit" SIGQUIT;

while true
do
    echo "To infinity and beyond";
    sleep 2;
done
