#!/usr/bin/env bash
# displays infinity and beyond indefinitely With a sleep 2 in between.

# Trap the SIGTERM signal and display the message
trap "echo 'I am invincible!!!'" SIGTERM


for ((i = 1; ; i++))
do
    echo "To infinity and beyond"
    sleep 2
done