#!/usr/bin/env bash
# Bash script that displays : 
# The content of the current directory.
# In a list format.
# Where only the part of the name after the first dash is displayed.
for ls in *; do
    if [[ -f "$ls" && ! "$ls" =~ ^\..* ]]; then
        echo "$ls" | rev | cut -d '-' -f1 | rev
    fi
done
