#!/usr/bin/env bash
# This script configures Nginx to run as the 'nginx' user and listen on port 8080.

# Release port 8080 by stopping Apache2 if it's running
pkill apache2

# Define the path to Nginx configuration file
nginx_conf="/etc/nginx/nginx.conf"

# Set owner permissions for the Nginx configuration file
chmod 744 $nginx_conf

# Configure Nginx to run as nginx user
sed -i "s/#user www-data;/user nginx;/" $nginx_conf

# Update the default site configuration to listen on port 8080
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default

# Ensure nginx user has necessary permissions
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx

# Start Nginx service as nginx user
sudo -u nginx service nginx start
