#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
pkill apache2
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 744 /etc/nginx/nginx.conf
su nginx -c "service nginx restart"
